### ISSUE TITLE
可不可以提供一下生成json的脚本，我这边生成的会报错，是编码格式的问题吗？

### ISSUE THREAD

**Issue by FelixZhang7** [StanleyLsx/llms_tool#39]
![image](https://github.com/StanleyLsx/llms_tool/assets/32166605/5eae055e-9adb-4e0a-8491-576c6366db04)

**Comment by StanleyLsx** [comment]
> ![image](https://user-images.githubusercontent.com/32166605/262954774-5eae055e-9adb-4e0a-8491-576c6366db04.png)

可以截图让我看下你数据集的格式吗？

**Comment by FelixZhang7** [comment]
> 
![image](https://github.com/StanleyLsx/llms_tool/assets/32166605/e35f7832-a385-47b6-9b51-fb15d2e916f4)

**Comment by StanleyLsx** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/32166605/263150679-e35f7832-a385-47b6-9b51-fb15d2e916f4.png)


[看起来你那边第一步读取数据就出问题了，原因可能是train_file_dir里面有history这个key而validation_file_dir里面的数据没有这个key建议，我这需要兼容，暂时可以通过下面方法解决：
1. 确定一下train_file_dir的file path是正确的，关闭do_eval不要做evaluate然后再训练；
2. 如果需要evaluate暂时需要处理一下train_file_dir和validation_file_dir的数据格式，使其要么都有hository这个key或者都没有。

**Comment by FelixZhang7** [comment]
> 

感谢，json问题解决了。还有一个问题，目前项目只支持lora的权重合并吗？prompt tuning和prefix tuning的权重没有如何合并和加载呢？

AttributeError: 'QWenLMHeadModel' object has no attribute 'merge_and_unload'
