### ISSUE TITLE
sft时不输出eval loss

### ISSUE THREAD

**Issue by shaomai00** [StanleyLsx/llms_tool#60]
您好，请问sft训练过程中为什么不打印eval loss呢？除了在这里加上eval_dataset，还需要注意哪里吗？
https://github.com/StanleyLsx/llms_tool/blob/main/engines/train.py#L203

**Comment by StanleyLsx** [comment]
> 您好，请问sft训练过程中为什么不打印eval loss呢？除了在这里加上eval_dataset，还需要注意哪里吗？ https://github.com/StanleyLsx/llms_tool/blob/main/engines/train.py#L203

do_eval也需要设置为True

**Comment by shaomai00** [comment]
嗯嗯 设置了，这里默认就是True，我没有改
https://github.com/StanleyLsx/llms_tool/blob/main/config.py#L264

**Comment by shaomai00** [comment]
已解决，加入--evaluation_strategy steps
