### ISSUE TITLE
关于模型预训练

### ISSUE THREAD

**Issue by clclclaiggg** [stanleylsx/llms_tool#67]
你好，请问一下llama2-7B模型预训练需要多少的GPU资源呢

**Comment by stanleylsx** [comment]
> 你好，请问一下llama2-7B模型预训练需要多少的GPU资源呢

可以看一下下面这篇文章：
https://zhuanlan.zhihu.com/p/624740065

**Comment by clclclaiggg** [comment]
谢谢您的解答

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年10月27日 18:23 |
| 收件人 | stanleylsx/llms_tool ***@***.***> |
| 抄送人 | clclclaiggg ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [stanleylsx/llms_tool] 关于模型预训练 (Issue #67) |

你好，请问一下llama2-7B模型预训练需要多少的GPU资源呢

可以看一下下面这篇文章：
https://zhuanlan.zhihu.com/p/624740065
