### ISSUE TITLE
SFT数据集字段

### ISSUE THREAD

**Issue by FoolMark** [stanleylsx/llms_tool#74]
instruction 和 input有什么区别？

**Comment by stanleylsx** [comment]
> instruction 和 input有什么区别？

在大型模型的SFT（Supervised Fine-Tuning）数据集中，"instruction"（指导）和"input"（输入）之间存在以下区别：

1. Instruction（指导）：指导是针对模型的指令或提示，用于指导模型生成正确的输出。它可以是一段自然语言文本，描述所需的操作、结果或行为。指导的目的是帮助模型理解任务要求并生成相应的输出。

2. Input（输入）：输入是指模型接收的原始数据，通常是一个或多个自然语言句子。输入可能包含与指导相关的信息，但它不直接指示模型要执行的操作。相反，模型需要从输入中提取信息并结合指导生成适当的输出。

总的来说，指导是一种指示模型所需操作或结果的指令，而输入是模型用于生成输出的原始数据。指导提供任务的上下文和目标，而输入则提供了需要处理的具体信息。

Answered by chatgpt
