### ISSUE TITLE
AttributeError: 'DataManager' object has no attribute 'generating_args_preprocess'

### ISSUE THREAD

**Issue by autaugaville** [stanleylsx/llms_tool#75]
Traceback (most recent call last):
  File "/root/retrieve/prm/exp0_test0/main.py", line 46, in <module>
    train.supervised_fine_tuning(test=True)
  File "/root/retrieve/prm/exp0_test0/engines/train.py", line 271, in supervised_fine_tuning
    gen_kwargs = self.data_manager.generating_args_preprocess(gen_kwargs)
AttributeError: 'DataManager' object has no attribute 'generating_args_preprocess'

**Comment by stanleylsx** [comment]
> Traceback (most recent call last): File "/root/retrieve/prm/exp0_test0/main.py", line 46, in train.supervised_fine_tuning(test=True) File "/root/retrieve/prm/exp0_test0/engines/train.py", line 271, in supervised_fine_tuning gen_kwargs = self.data_manager.generating_args_preprocess(gen_kwargs) AttributeError: 'DataManager' object has no attribute 'generating_args_preprocess'

已修复
