### ISSUE TITLE
sft train报错

### ISSUE THREAD

**Issue by langgege-cqu** [StanleyLsx/llms_tool#76]
<img width="1130" alt="image" src="https://github.com/stanleylsx/llms_tool/assets/48318956/a307f04d-1c2d-4554-ac4d-9b27bcafe715">
数据集、模型都能正常加载，train就报错，是因为拓展词表的原因吗（我不需要拓展词表）

**Comment by stanleylsx** [comment]
> <img alt="image" width="1130" src="https://private-user-images.githubusercontent.com/48318956/299914228-a307f04d-1c2d-4554-ac4d-9b27bcafe715.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MTY2OTQsIm5iZiI6MTcyNjcxNjM5NCwicGF0aCI6Ii80ODMxODk1Ni8yOTk5MTQyMjgtYTMwN2YwNGQtMWMyZC00NTU0LWFjNGQtOWIyN2JjYWZlNzE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDAzMjYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NmQxZjA1NGY2YWU1NGQzNzYyOTgzMmQ2MGNiNGJhMGI3ODFhNmQzNGRhMzQ3ZDZhYjE3YjczYjNiM2UxODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ka2EuGkBLUL5Z4OBoI7gdfqjSTJo9e4NlGch6G4kBGs"> 数据集、模型都能正常加载，train就报错，是因为拓展词表的原因吗（我不需要拓展词表）

配置是怎么样的？拓展词表是可以关闭的
